config/routes.rb
Rails.application.routes.draw do

  get 'consulta/:Codigo_Empleado' => 'volantes#consulta', as: :empleado
  get 'error' => 'volantes#noEmpleado'

  get '/usuarios' => 'users#index'
  get '/new/usuario' => 'users#new'
  post '/new/usuario' => 'users#create'
  get 'usuario/:id/edit' => 'users#edit', as: :edit
  patch 'usuario/:id' => 'users#update', as: :update

  get 'user/:id/editPerfil' => 'users#editPerfil', as: :editPerfil
  patch 'user/:id' => 'users#updatePerfil', as: :updatePerfil
  delete 'user/:id' => 'users#destroy', as: :delete

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  root 'sessions#new'

end

app/models/nomina_comprobante_det.rb
class NominaComprobanteDet < ActiveRecord::Base
  belongs_to :nomina_comprobante_pago
  self.table_name = 'vw_NominaComprobanteDet'
  self.primary_key =('Codigo_nomina')

end

app/models/nomina_comprobante_pago.rb
class NominaComprobantePago < ActiveRecord::Base
  has_many :nomina_comprobante_dets, :foreign_key => 'Codigo_Empleado'
  self.table_name = 'vw_NominaComprobantePago'
  self.primary_key = ('Codigo_Empleado')
  scope :consultaEmpleado, -> { where(Ano_Correspondiente: '2016', Mes_correspondiente:'11', Codigo_Empleado: '1963', Periodo:'2' ) }


end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :correo, presence:  { message: 'No puede dejarse vacío' },uniqueness: { message: 'ya existe!  '}, email:  {message: "Invalido, Utilizar @/gmail/hotmail/labreferencia/.com, ejemplo: example@labreferencia.com" }
  validates :codigo_empleado,uniqueness: { message: 'ya existe!  '}, presence: { message: 'No puede dejarse vacío' }
  validates :password, presence: { message: 'No puede dejarse vacío'},length: {minimum: 8, maximum: 25, :message =>", El Minimo de caracteres permitido es 8"}
  validates :tipo, presence: {message: 'No puede dejarse vacio'}

  def admin?
    self.tipo =='admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  helper_method :current_user

 

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  def requiere_usuario
    redirect_to '/login' unless current_user
  end
  def requiere_usuario_admin
    redirect_to '/login' unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
   user = User.find_by_correo(params[:correo])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.codigo_empleado
      if user.tipo =='admin'
        session[:user_id] = user.id
        redirect_to '/usuarios'
      else
      redirect_to empleado_path(session[:user_id])
      end

    else
      redirect_to login_path, flash: {alert: "Contraseña o Usuario Invalido"}
      #render 'sessions/new'
    end


  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :requiere_usuario_admin,  only: [:index, :edit,:update,:new,:create]
  def index
    @usuarios = User.paginate(:page => params[:page], :per_page => 10).order('codigo_empleado ASC')

  end

  def edit
    @user = User.find(params[:id])
  end

  def editPerfil
    @user = User.find(params[:id])
  end

  def updatePerfil
    @user = User.find_by(params[:codigo_empleado])
    if @user.update(params_user_perfil)
      redirect_to 'error'
    else
      render 'users/editPerfil'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(params_user_edit)
      redirect_to '/usuarios'
    else
      render 'edit'
    end
  end

    def new
      @user = User.new
    end

    def create
      @user = User.new(params_user)
      if @user.save
        redirect_to '/usuarios'
      else
        render  'new'
      end
    end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to '/usuarios', :notice =>'Usuario eliminado correctamente '
    end
  end



  private
  def params_user
    params.require(:user).permit(:codigo_empleado,:correo,:password,:tipo)
  end

  def params_user_edit
    params.require(:user).permit(:codigo_empleado,:correo,:password,:tipo,:activo)
  end

  def params_user_perfil
    params.require(:user).permit(:password)
  end

end

app/controllers/volantes_controller.rb
class VolantesController < ApplicationController


  def consulta


  begin
    if params[:Mes_correspondiente].present? && params[:Periodo].present? && params[:Ano_Correspondiente].present?

      @Consulta = NominaComprobantePago.where(['Mes_correspondiente=? AND Periodo = ? AND Ano_Correspondiente=? ' ,params[:Mes_correspondiente], params[:Periodo], params[:Ano_Correspondiente]],).order('Ano_Correspondiente Desc').find(session[:user_id])
      @nomina = @Consulta.Codigo_Nomina
      @Detalle =@Consulta.nomina_comprobante_dets.where(Codigo_nomina: @nomina)



   else

    @Consulta = NominaComprobantePago.where(:Codigo_Empleado => params[:Codigo_Empleado]).order('Ano_Correspondiente Desc, Mes_correspondiente Desc, Periodo Desc').find(session[:user_id])
    @nomina = @Consulta.Codigo_Nomina
    @Detalle =@Consulta.nomina_comprobante_dets.where(Codigo_nomina: @nomina)



    end
  rescue
    redirect_to empleado_path, flash: {notice: "=> Registro no encontrado <="}
  end
end



  def noEmpleado

  end


  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/volantes_helper.rb
module VolantesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VolantePag</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'logo.ico'%>
</head>
<body>

<%= yield %>

<footer id="pie">
  <p>Referencia Laboratorio Clínico &copy; Derechos reservados 2017</p>
</footer>

</body>
</html>

app/views/users/edit.html.erb
<header>
  <%=link_to (image_tag 'logo.png'), usuarios_path %>

</header>
<div class="container">
  <div class="registro">

    <h1 class="to">EDITAR USUARIO</h1>

    <%= form_for  @user, url: update_path(@user) do |f| %>
        <% if @user.errors.any? %>
            <div id="errorExplanation">
              <ul>
                <% @user.errors.full_messages.each do |msg| %>
                    <li  class="alert alert-danger" role="alert" ><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
        <div class="control-group error">
          <div class="controls ">
            <%= f.text_field :codigo_empleado, :placeholder => 'Codigo Empleado', :class=>"form-control inputt" ,:disabled =>true%>
          </div>
          <div class="controls">
            <%= f.text_field :correo , :placeholder => 'Correo Electronico', :class=>"form-control inputt" %>
          </div>
          <div class="controls">
            <%= f.password_field :password, :placeholder => 'Password',:class=>"form-control inputt" %>
          </div>
          <div class="controls">
            <%= f.text_field :tipo, :placeholder => 'Tipo de cuenta ',:class=>"form-control inputt" %>
          </div>
        </div>
        <div class="controls">
          <%= f.text_field :activo, :placeholder => 'Estatus',:class=>"form-control inputt" %>
        </div>
        <div class="actions"><%= f.submit 'Enviar', :class=>'btn btn-success btn2' %></div>
    <% end %>
  </div>
</div>

app/views/users/editPerfil.html.erb
<header>
  <%=link_to (image_tag 'logo.png') %>

</header>
<div class="container">
  <div class="registro">

    <h1 class="to">EDITAR PERFIL</h1>

    <%= form_for  @user, :url => updatePerfil_path(@user) do |f| %>
        <% if @user.errors.any? %>
            <div id="errorExplanation">
              <ul>
                <% @user.errors.full_messages.each do |msg| %>
                    <li  class="alert alert-danger" role="alert" ><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
        <div class="control-group error">
          <div class="controls ">
            <%= f.text_field :codigo_empleado, :placeholder => 'Codigo Empleado', :class=>"form-control inputt" ,:disabled =>true%>
          </div>
          <div class="controls">
            <%= f.text_field :correo , :placeholder => 'Correo Electronico', :class=>"form-control inputt" %>
          </div>
          <div class="controls">
            <%= f.password_field :password, :placeholder => 'Password',:class=>"form-control inputt" %>
          </div>

        </div>

        <div class="actions"><%= f.submit 'Enviar', :class=>'btn btn-success btn2' %></div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<header>
  <%= image_tag 'logo.png'%>
  <div class="perfil">
    <p class="parrafo"><strong>Bienvenido :  </strong><%=current_user.correo%></p>
    <span> <%=link_to 'Cerrar sesion',  logout_path, method: :delete,class: 'link' %></span>

  </div>
</header>

<div class="container">



  <br>
  <h1 >Lista de Usuarios Activos: </h1>

  <div class="menu">
  <span style="align-content:  center">  <%=link_to 'Registrar nuevo usuario', new_usuario_path, :class => 'btn btn-info'%></span>

  </div>
  <table class="table table-bordered">
    <thead>

    <tr class="ttitulo">
      <th>CODIGO EMPLEADO</th>
      <th>CORREO</th>
      <th>ACTIVO</th>
      <th>TIPO DE USUARIO</th>
      <th colspan="2" style="text-align: center">ACCIÓN</th>

    </tr>
    </thead>

    <tbody>
    <%@usuarios.each do |user|%>
    <tr>
      <td><%=user.codigo_empleado %></td>
      <td><%= user.correo%></td>
      <td><%= user.activo%></td>
      <td><%= user.tipo%></td>
      <td style="text-align: center"><%=link_to 'Editar',edit_path(user),:class => 'btn btn-warning' %></td>
      <%if user.tipo !='admin' %>
      <td style="text-align: center"><%=link_to 'Eliminar',   { action: :destroy, id: user.id }, method: :delete, data: { confirm: 'Esta seguro de eliminar este usuario?' },:class => 'btn btn-danger' %></td>
      <%end%>

    </tr>
    </tbody>
        <%end%>
  </table>
  <%= will_paginate @usuarios, renderer: BootstrapPagination::Rails, :class=>'paginacion' %>
</div>

app/views/users/new.html.erb
<header>
  <%=link_to (image_tag 'logo.png'), usuarios_path %>


</header>
<div class="container">
  <div class="registro">

<h1 class="to">Registro de Nuevo Usuario</h1>

<%= form_for  @user, url: new_usuario_path(@user) do |f| %>
        <% if @user.errors.any? %>
            <div id="errorExplanation">
              <ul>
                <% @user.errors.full_messages.each do |msg| %>
                    <li  class="alert alert-danger" role="alert" ><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
        <div class="control-group error">
    <div class="controls ">
      <%= f.text_field :codigo_empleado, :placeholder => 'Codigo Empleado',:class=>"form-control inputt"%>
    </div>
    <div class="controls">
      <%= f.text_field :correo , :placeholder => 'Correo Electronico',:class=>"form-control inputt"%>
    </div>
    <div class="controls">
      <%= f.password_field :password, :placeholder => 'Password',:class=>"form-control inputt"%>
    </div>
          <div>
            <%= f.text_field :tipo, :placeholder => 'Tipo de cuenta ',:class=>"form-control inputt" %>

          </div>
          </div>
          <div class="actions"><%= f.submit 'Enviar', :class=>'btn btn-success btn2' %></div>
<% end %>
  </div>
</div>

app/views/volantes/consulta.html.erb
<header>
  <%= image_tag 'logo.png'%>

  <div class="perfil">
    <%if @Consulta.Codigo_Empleado.present?%>
        <p class="parrafo"><strong>Bienvenido :  </strong><%=@Consulta.NombreEmp%></p>
       <!-- <#%=link_to 'Editar Perfil',  editPerfil_path(@Consulta.Codigo_Empleado), class: 'linkk'%>-->
        <%=link_to 'Cerrar sesion',  logout_path, method: :delete,class: 'link' %>
    <%end%>
  </div>

</header>

<br>
<br>

<div class="container">

<div class="formulario  ">
  <h6  style="margin-left: 85px"> <strong style="color: #B00100">Nota:</strong> Filtrar por todos los parametros</h6>

  <%= form_tag empleado_path, method: :get do%>
      <div class="form-group ">
        <div class="col-md-4">
          <div class="row">
          <div class="col-md-4">

        <%= select_tag :Mes_correspondiente, options_for_select([['Mes', ""], '1', '2','3', '4','5', '6','7', '8','9', '10','11', '12']), class: 'form-control size' %>
            <%= submit_tag "Buscar", name: nil, class: 'btn btn-primary btn-md '  %>
          </div>

          <div class="col-md-4">
            <%= select_tag :Periodo, options_for_select([['Periodo', ""], '1', '2']), class: 'form-control size' %>

          </div >

          <div class="col-md-4">
            <%= select_tag :Ano_Correspondiente, options_for_select([['Año', ""], Time.now.year,  Time.now.year - 1, Time.now.year - 2]), class: 'form-control size' %>
          </div>
          </div>
        </div>

      </div>


  <%end%>
</div>

  <%if flash[:notice]%>
  <div class="alert alert-danger" style="float: right; margin-right: 500px">

     <p><%= flash[:notice]%></p>

  </div>
  <%end%>

  <div class="row ">
    <div class="col-md-8">
      <h1>Información:</h1>
    </div>
    <div class="col-md-4 impri">
      <input type="button" class="btn btn-success" style="width: 100px; font-weight: bold;" value="Imprimir" onclick="window.print()">
    </div>
  </div>
  <br>

  <div class="row">
    <div class="col-md-4">
      <p><strong>Código: </strong> <%= @Consulta .Codigo_Empleado %> </p>
      <p><strong>Nombres: </strong><%= @Consulta .NombreEmp%> </p>
      <p><strong>Cedula/passporte: </strong> <%= @Consulta .Cedula %> </p>
      <p><strong>Sueldo Bruto: </strong>  <%=  number_to_currency(@Consulta.Sal_Base)%></p>
    </div>

    <div class="col-md-4">

      <p><strong>Sucursal: </strong></p>
      <p><strong>Cargo:</strong>  <%= @Consulta .Nombre_Cargo %></p>
      <p><strong>Depto: </strong><%= @Consulta .SubGrupoNom %>  </p>
      <p><strong>Mes Correspondiente:</strong>  <%=@Consulta .Mes_correspondiente %></p>

    </div>

    <div class="col-md-4">
      <p><strong>Cuenta Banco: </strong> <%= @Consulta .Cuenta_Bancaria%> </p>

      <p><strong>Año Correspondiente: </strong><%= @Consulta.Ano_Correspondiente%></p>
      <p><strong>Periodo Correspondiente: </strong><%= @Consulta.Periodo%></p>
      <p><strong>Fecha desde: </strong><%= @Consulta.Fecha_Desde.to_formatted_s(:short) %> <strong> Hasta: </strong> <%=@Consulta.Fecha_Hasta.to_formatted_s(:short) %></p>


    </div>
  </div>

  <br>

  <table  class="table table-bordered">
    <thead>

    <tr class="ttitulo">
      <th colspan="2" >Ingreso</th>
      <th colspan="2">Descuento</th>
    </tr>

    <tr class="trConcepto">
      <td>Concepto</td>
      <td>Valor</td>
      <td>Concepto</td>
      <td>Valor</td>
    </tr>

    </thead>

    <tbody>
    <!--Aqui ira el array para traer los ingresos e ingresos respecto al concepto y monto-->
    <% @Detalle.each do |d|%>

    <tr>
     <%if d.Concepto =='I'%>
      <td><%=d.Desc_Nov %></td>
      <td align="right"><%= number_to_currency(d.ValNov) %></td>
          <td></td>
          <td></td>


    <%end%>
      <%if d.Concepto == 'D'%>
          <td></td>
          <td></td>
      <td><%=d.Desc_Nov %></td>
      <td align="right"><%= number_to_currency(d.ValNov) %></td>
   <%end%>
    </tr>


  <%end%>

    </tbody>

    <tfoot>
    <tr class="trConcepto">
      <td colspan="2" align="right"><strong> Total Ingresos : </strong> <%= number_to_currency(@Consulta.Total_Ingresos) %></td>
      <td colspan="2" align="right"><strong>Total Descuentos : </strong> <%= number_to_currency(@Consulta.Total_Descuentos )%></td>
    </tr>
    <tr class="tpie">
      <td colspan="2"></td>
      <td colspan="2"><strong>Total Neto:</strong> <%= number_to_currency(@Consulta.Neto_Pagado) %></td>
    </tr>
    </tfoot>

  </table>

</div>

app/views/volantes/noEmpleado.html.erb
<header>
  <%= image_tag 'logo.png'%>


</header>
<p style="text-align: center"><%=link_to 'Regresar al Login', root_path%></p>
<div class="alert alert-danger" role="alert" style="width: 40%; height: 50%; margin-left: 600px" >
<p style="text-align: center; font-weight: bold; font-size: 16px">Contraseña <br> O <br> Correo incorrecto</p>
</div>